name: .NET

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2         
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore DemoApi.sln

    - name: Build Solution
      run: dotnet build --no-restore DemoApi.sln

    - name: Run Unit Test
      run: dotnet test DemoApiTest\DemoApiTest.csproj --no-restore --no-build