name: .NET

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore DemoApi.sln
    - name: Build
      run: dotnet build --no-restore DemoApi.sln
    - name: Test
      run: dotnet test DemoApiTest//DemoApiTest.csproj --no-build --verbosity normal
